### ISSUE TITLE
connection closed by server

### ISSUE THREAD

**Issue by nottooloud** [bitfocus/companion-module-cisco-webex-websocket#2]
Entered address, ID, and password (I added a password) for a C60 running TC6.2. Module status is connection closed by server.

I have an early build Yuri sent me that still works.

**Comment by nottooloud** [comment]
same results with a C20 on TC 7.3
connection closed by server

**Comment by JeffreyDavidsz** [comment]
Thanks for testing! I'll check tomorrow for you, I'm testing through a vpn with no issues connecting.
I assume you have websocket enabled on the devices? The build from Yuri might use a different connection method.

**Comment by nottooloud** [comment]
> websocket enabled

If that's configuration Network Services HTTPS Mode On, then yes. I can control the codecs with HTML addressing.

The build from Yuri isn't his early stuff, it's a build from after he wrapped his code into yours.

**Comment by bwentzel** [comment]
Please note xAPI over Websocket support was released in CE v9.7.1.

**Comment by nottooloud** [comment]
Perhaps the project description should include a list of the target devices and required software releases. Some of the other attempts at this module did use XML. They were encouraged to bring their work here.

**Comment by JeffreyDavidsz** [comment]
@nottooloud besides the HTTPS did you put the websocket followhttpservice on? That is probably only available from a certain version.
I've asked to see if ssh is supported below version 9.7

**Comment by nottooloud** [comment]
XML, SSH, and HTML are all supported as least as far back as TC5, which is the oldest device I have. Websocket evidently not so much.

**Comment by JeffreyDavidsz** [comment]
Yes no worries ssh will be in the next update

**Comment by nottooloud** [comment]
Genius. That should be much more responsive for camera controls. I have someone working on a dedicated app for camera PTZ, settings, and presets. It got way better when he moved from XML to SSH.

**Comment by JeffreyDavidsz** [comment]
Update is ready, be aware it's a test version. I'll close this when you found something, just open a new issue
