### ISSUE TITLE
xCommand without Params

### ISSUE THREAD

**Issue by RO55INGER** [bitfocus/companion-module-cisco-webex-websocket#9]
I am trying to issue xCommands that don't need params, like 'xCommand Video Input MainVideo Mute'. Those command do not work. I get an error in the log stating that the JSON string is malformed in the custom xCommand. How can I use those commands?

Thanks for the great module, it really helps us out with events!
RO55

**Comment by JeffreyDavidsz** [comment]
Did you try to do an empty param like `{}`?

**Comment by RO55INGER** [comment]
That did the trick, thanks! Didn't think of that...
